### ISSUE TITLE
Bug using workflow:dump

### ISSUE THREAD

**Issue by cgrisar** [RingierIMU/state-workflow#1]
When using workflow:dump, the command would refuse to find the workflow I created.

It turns out `$model->workflow()` is the culprit.

In HasWorkflowTrait.php

```
public function workflow()
    {
        if (!$this->workflow) {
            $this->workflow = app(WorkflowRegistryInterface::class)->get($this, $this->configName());
        }

        return $this->workflow;
    }
```

However, $this->configName() returns the lower case name of the class, where I'd need the name of the workflow.

So, I created a new function in HasWorkflowTrait

```
public function workflowNameArgument($workflowName)
    {
        if (!$this->workflow) {
            //$this->workflow = app(WorkflowRegistryInterface::class)->get($this, $this->configName());
            $this->workflow = app(WorkflowRegistryInterface::class)->get($this, $workflowName);
        }

        return $this->workflow;
    }
```

That I call in StateWorkflowDumpCommand.php

**Comment by norbybaru** [comment]
@cgrisar can you share your `config/workflow.php` file? I want to see how it looks

**Comment by norbybaru** [comment]
@cgrisar will close this issue for now until comes back up
