### ISSUE TITLE
Support for laravel/framework v6.5.1

### ISSUE THREAD

**Issue by anthonytp** [RingierIMU/state-workflow#7]
When installing the library with composer it fails with the error:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Conclusion: remove laravel/framework v6.5.1
>     - Conclusion: don't install laravel/framework v6.5.1
> ...

The only mention of the Laravel framework version is to add a line to the config/app.php file if using <=5.5, but nothing about support for later versions.

What's the latest version of the framework this project supports?

**Comment by datashaman** [comment]
Hi there @anthonytp sorry about the wait, we've merged in support for Laravel 6, and added a workflow in GitHub Actions to build for various PHP and Laravel configs.
